ChingChong/ChingChong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('account/', include("account.urls")),
    path('posts/', include("posts.urls")),
    # path('api/', include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChingChong/main/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="main/index.html"), name="index"),
    path('menu', TemplateView.as_view(template_name="main/menu.html"), name="menu"),
    path('contacts', TemplateView.as_view(template_name="main/contacts.html"), name="contacts"),
    path('subs', views.sub, name="subscription"),
    path('api/search_city', views.search_city),
    path('api/profile_update', views.profile_update, name="profile_update"),
    path('api/unique/username', views.unique_name),
    path('api/unique/email', views.unique_email),
]

ChingChong/posts/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('create', views.postCreate, name='create_post'),
    path('all', views.postAll, name="all_posts"),
    path('mine', views.postMine, name="my_posts"),
    path('edit/<int:id>', views.postEdit, name="edit_post"),
    path('delete/<int:id>', views.postDelete, name="delete_post"),
    path('api/like/<int:id>', views.postLike, name="api_post_like"),
    path('api/dislike/<int:id>', views.postDislike, name="api_post_dislike"),
    path('api/getPosts', views.apiPosts, name="api_get_posts"),
]

ChingChong/posts/models.py
from django.db import models
from account.models import User
from main.models import Restaurant

# Create your models here.
class Post(models.Model):
    RATINGTYPE = [ (1, "1 Звезда"), (2,"2 Звезды"), (3, "3 Звезды"), (4, "4 Звезды"), (5, "5 Звезд") ]
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Отправитель")
    restaurant = models.ForeignKey(Restaurant, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Ресторан")
    rating = models.IntegerField("Рейтинг", choices=RATINGTYPE, default='5', blank=False)
    review = models.TextField("Отзыв", blank=False, max_length=1024)
    # likes = models.IntegerField("Лайки", default=0)
    # dislikes = models.IntegerField("Дизлайки", default=0)

    publish = models.BooleanField("Опубликован", default=False)

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.publish and not self.sender:
            self.delete()
    

class PostInfo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    RATINGTYPE = [ (0, "None"), (1,"Like"), (-1, "Dislike"), ]
    rating = models.IntegerField("Оценка", choices=RATINGTYPE, default=0, blank=False)

    class Meta:
        unique_together = ("user", "post")

    # @classmethod
    # def set_user_rating(cls, post, user, rating):
    #     obj, created = cls.objects.get_or_create(post=post, user=user)
    #     if not created:
    #         obj.rating = rating
    #         obj.save()
    #     else:
    #         obj.rating = rating
    #         obj.save()
        
    #     # Обновляем количество лайков/дизлайков у поста
    #     if rating == 1:
    #         post.likes += 1
    #     elif rating == -1:
    #         post.dislikes += 1
    #     post.save()

ChingChong/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post
from main.models import Restaurant
from django.shortcuts import get_object_or_404

class PostsCreationForm(forms.ModelForm):
    def clean_restaurant(self):
        restaurant = self.data.get('restaurant')
        if restaurant is None:
            return None
        
        # Проверяем, существует ли ресторан
        try:
            restaurantObject = Restaurant.objects.get(pk=restaurant)
            return restaurantObject
        except Restaurant.DoesNotExist:
            raise ValidationError('Incorrect Restaurant selected!!')

    class Meta:
        model = Post
        fields = ['sender', 'restaurant','rating', 'review']

# class PostsEditForm(forms.ModelForm):
#     def clean_restaurant(self):
#         restaurant = self.data.get('restaurant')
#         if restaurant is None:
#             return None
        
#         # Проверяем, существует ли ресторан
#         try:
#             restaurantObject = Restaurant.objects.get(pk=restaurant)
#             return restaurantObject
#         except Restaurant.DoesNotExist:
#             raise ValidationError('Incorrect Restaurant selected!!')

#     class Meta:
#         model = Post
#         fields = ['sender', 'restaurant','rating', 'review']

ChingChong/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .forms import *
from main.models import Restaurant
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage


def postAll(req):
    page = int( req.GET.get('page', 1) )
    filter = int(req.GET.get('filter', '0'))
    paginator = getPosts( filter )

    try:
        back = page - 1 if paginator.page(page).has_previous() else None
        front = page + 1 if paginator.page(page).has_next() else None

    except EmptyPage:
        back = None
        front = None

    nav = { "back": back, "front": front, "range": paginator.page_range}
    return render(req, "posts/AllPosts.html", {"page": page, "filter": filter, "nav": nav, "restaurants": Restaurant.objects.all()})

# Получаем посты оформленные шаблонизатором
def apiPosts(req):
    page = int( req.GET.get('page', 1) )
    paginator = getPosts( int(req.GET.get('filter', '0')) )

    try:
        raw_html = render(req, "posts/api_posts.html", {"posts": paginator.page(page).object_list})
    except EmptyPage:
        raw_html = render(req, "posts/api_posts.html", {"posts": None})
    
    return JsonResponse({'html': raw_html.content.decode()})


# Вспомогательный метод который возвращает посты(QuerySet) + пагинация
def getPosts(filter):
    # Если установлен фильтр, то фильтруем посты по городу.
    if (filter != 0):
        posts = Post.objects.filter(publish=True, restaurant__pk=filter).order_by('-pk')
    else:
        posts = Post.objects.filter(publish=True).order_by('-pk')

    return Paginator(posts, 4, allow_empty_first_page=False)
    

@login_required
def postCreate(req):
    new_Post = PostsCreationForm()
    if req.method == 'POST':
        data = req.POST.copy()

        data['sender'] = req.user
        if data['restaurant'] == '0':
            data['restaurant'] = None
        
        new_Post = PostsCreationForm(data)
        if new_Post.is_valid():
            new_Post.save()
            # PostsCreationForm.add_error(new_Post, None, "Your post has been sent for moderation")
            return redirect("my_posts");

    return render(req, "posts/Book.html", {"form": new_Post, "cities": Restaurant.objects.all()})

@login_required
def postLike(req, id):
    post = get_object_or_404(Post, pk=id)

    if PostInfo.objects.filter(post=post, user=req.user).exists():
        info = PostInfo.objects.get(post=post, user=req.user)
        if info.rating == 1:
            info.delete()
        else:
            info.rating = 1
            info.save()
    else:
        info = PostInfo(post=post, user=req.user, rating=1)
        info.save()


    return redirect("all_posts")


@login_required
def postDislike(req, id):
    post = get_object_or_404(Post, pk=id)

    if PostInfo.objects.filter(post=post, user=req.user).exists():
        info = PostInfo.objects.get(post=post, user=req.user)
        if info.rating == -1:
            info.delete()
        else:
            info.rating = -1
            info.save()
    else:
        info = PostInfo(post=post, user=req.user, rating=-1)
        info.save()


    return redirect("all_posts")

@login_required
def postMine(req):
    posts = Post.objects.filter(sender=req.user).order_by('-pk')
    return render(req, "posts/MyPosts.html", {"posts": posts})


@login_required
def postEdit(req, id):
    post = get_object_or_404(Post, pk=id)
    postEditForm = PostsCreationForm(instance=post) # Can be used to edit Post too


    if (req.user == post.sender and not post.publish) or (req.user.has_perm('posts.change_post')):
        if req.method == 'POST':
            data = req.POST.copy()

            data['sender'] = req.user
            if data['restaurant'] == '0':
                data['restaurant'] = None
            
            postEditForm = PostsCreationForm(data=data, instance=post)
            if postEditForm.is_valid():
                postEditForm.save()
                # PostsCreationForm.add_error(new_Post, None, "Your post has been edited")
                return redirect("my_posts")

        return render(req, "posts/EditBook.html", {"form": postEditForm, "cities": Restaurant.objects.all()})
    
    else:
        raise PermissionDenied("You cant edit other's posts")
    
def postDelete(req, id):
    post = get_object_or_404(Post, pk=id)
    if (req.user == post.sender and not post.publish) or (req.user.has_perm('posts.delete_post')):
        post.delete()
        return redirect("my_posts")

ChingChong/templates/posts/1MyPosts.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="ru">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <title>
   Мои отзывы
  </title>
  <link href="{% static 'css/MyPosts.css' %}" rel="stylesheet"/>
  <link href="{% static 'img/Logo.webp' %}" rel="shortcut icon"/>
  <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" rel="stylesheet"/>
 </head>
 <body>
  <script crossorigin="anonymous" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js">
  </script>
  {% comment %} <header class="menu">
   <a href="{% url 'index' %}">
    <img class="GoToMain" src="{% static 'img/Logo.webp' %}"/>
   </a>
   <div class="container-fluid">
    <div class="col badcol Panel">
     <div class="row badrow BeforeKnopka">
      <div class="col MenuTable">
       <a class="GoToMenu" href="{% url 'menu' %}">
        Меню
       </a>
       <a class="GoToTeam" href="{% url 'contacts' %}">
        О команде
       </a>
       <a class="GoToPosts" href="{% url 'all_posts' %}">
        Посты
       </a>
       <a href="{% url 'my_posts' %}">
        Мои отзывы
       </a>
      </div>
     </div>
     <div class="button-container">
      <button id="loginButton">
       Вход
      </button>
      <a class="hidden" href="{% url 'profile' %}" id="profile-button">
       <img alt="Личный кабинет" class="ImgIcon" src="{% static 'img/ИконкаАватара.png' %}">
       </img>
      </a>
      <button class="hidden" href="#" id="logoutButton">
       Выйти
      </button>
     </div>
     <div class="overlay" id="overlay">
     </div>
     <div class="form-container-authorization" id="loginForm">
      <form class="loginFormContent" method="POST">
       <div class="text-center">
        <label for="Email" style="color: white;">
         Логин
        </label>
        <br/>
        <input id="Email" name="username" style="width: 100%;" type="Email"/>
        <!-- required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"-->
        <br/>
        <br/>
        <label for="Password" style="color: white;">
         Пароль
        </label>
        <br/>
        <input id="Password" name="password" style="width: 100%;" type="Password"/>
        <!-- required
                              gpattern="^(?=.*[a-zA-Z])(?=.*\d)(?=.*_).{8,}$"
                              title="Пароль должен содержать хотя бы одну букву, одну цифру и ( _ ), и иметь минимум 8 символов."> -->
        <br/>
        <br/>
        <button class="BigButton" type="submit">
         Войти
        </button>
       </div>
       <div class="row BottomText badrow">
        <div class="col-6 TextSleva">
         <p>
          Нет Аккаунта?
         </p>
         <a class="WithoutUnderline" href="{% url 'registration' %}">
          Зарегистрироваться
         </a>
        </div>
        <div class="col-6 TextSprava">
         <p>
          Забыли пароль?
         </p>
         <a class="WithoutUnderline" href="{% url 'reset_password' %}">
          Восстановить пароль
         </a>
        </div>
       </div>
      </form>
      <script>
       const loginButton = document.getElementById('loginButton');
                  const overlay = document.getElementById('overlay');
                  const formContainer = document.getElementById('loginForm');
                  const passwordInput = document.getElementById('Password');
                  const submitButton = document.getElementById('submitButton');
                  const form = document.getElementById('loginFormContent');
                  const errorMessage = document.getElementById('errorMessage');
          
                  loginButton.addEventListener('click', function() {
                      overlay.classList.toggle('active');
                      formContainer.classList.toggle('active');
                  });
          
                  overlay.addEventListener('click', function() {
                    overlay.classList.remove('active');
                    formContainer.classList.remove('active');
                  });
      </script>
     </div>
     <div class="dropdown Knopka">
      <a aria-expanded="false" class="btn dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
       <img class="MenuKnopka" src="{% static 'img/Кнопка.png' %}"/>
      </a>
      <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu text-center">
       <li>
        <a class="GoToMenu" href="{% url 'menu' %}">
         Меню
        </a>
       </li>
       <hr/>
       <li>
        <a class="GoToTeam" href="{% url 'contacts' %}">
         О команде
        </a>
       </li>
       <hr/>
       <li>
        <a class="GoToPosts" href="{% url 'all_posts' %}">
         Посты
        </a>
       </li>
       <hr/>
       <li>
        <a class="GoToSelfPosts" href="{% url 'my_posts' %}">
         Мои отзывы
        </a>
       </li>
      </ul>
     </div>
    </div>
   </div>
  </header> {% endcomment %}
  {% include "menubar.html" %}
  <div class="ContainerOfAllPosts">
   <h1 class="Otz text-center">
    Мои отзывы
   </h1>
   <div class="OurCont">
     <a class="btn btn-dark d-flex col-3 mx-auto mb-3 justify-content-center" href="{% url 'create_post' %}">Создать Отзыв</a>
    {% for post in posts %}
    <div class="row OnePostContent">
      <div class="col OnePostBack PostWithoutCheck PostChecked">
       <div class="row">
        <div class="col-8 LeftPart">

          {% if post.publish %}
         <p class="Condition Condition2">
          Проверено администрацией
         </p>
         {% else %}
         <p class="Condition Condition1">
          На рассмотрении администрации
        </p>
        {% endif %}

        </div>
        <div class="col-4 ForButtonSetting LeftPadding RightPadding RightPart">
         <div class="row">
          <div class="col LeftPadding">
           {% if perms.posts.change_post or not post.publish %}
          <button class="ButtonSetting">
            <a href="{% url 'edit_post' post.pk %}"><img class="SettingIcon" src="{% static 'img/Шестерёнка.png' %}"/></a>
          </button>
          {% endif %}
          </div>
          <div class="col LeftPadding RightPadding ButtonText">
           {% comment %} <button class="MyBtn">
            Удалить
           </button> {% endcomment %}
           {% if perms.posts.change_post or not post.publish %}
            <a href="{% url 'delete_post' post.pk %}"><button class="MyBtn">Удалить</button></a>
          {% endif %}
          </div>
         </div>
        </div>
       </div>
       <h2 class="PersonName">
        Пользователь: {{post.sender.username}}
       </h2>
       <div class="row">
        <div class="col-3 MyCity">
         <p>
          Город: {{post.restaurant.adress|default:"--------"}}
         </p>
        </div>
        <div class="col-3 rating">
         <p>
          Рейтинг: {{post.get_rating_display}}
         </p>
        </div>
       </div>
       <p class="review">
        {{post.review}}
       </p>
       {% if post.publish %}
       <div class="row LikesAndDislikes">
        <div class="col-3 Likes">
         <div class="row">
          <div class="col-auto text-center">
           <p class="LikesAmount p1">
            Лайков:
           </p>
           <p class="amountL p1">
            {{post.postinfo_set.all|count_rating:1}}
           </p>
          </div>
          <div class="col-auto ForIcona">
            {% if user.is_authenticated %}
           {% comment %} <button class="Icona">
            <a href="{% url 'api_post_like' post.pk %}"><img class="LikeIcon" src="{% static 'img/Лайк.png' %}"/></a>
           </button> {% endcomment %}
           <a class="btn Icona">
            <img class="LikeIcon" data-pressed="{{post.postinfo_set.all|has_liked:user}}" data-post-id="{{post.pk}}" src="{% static 'img/like.png' %}"/>
           </a>
           {% endif %}
          </div>
         </div>
        </div>
        <div class="col-3 Dislikes">
         <div class="row">
          <div class="col-auto text-center">
           <p class="DislikesAmount p1">
            Дизлайков:
           </p>
           <p class="amountD p1">
            {{post.postinfo_set.all|count_rating:-1}}
           </p>
          </div>
          <div class="col-auto ForIcona">
            {% if user.is_authenticated %}
           {% comment %} <button class="Icona">
            <a href="{% url 'api_post_dislike' post.pk %}"><img class="DislikeIcon" src="{% static 'img/Дизлайк.png' %}"/></a>
           </button> {% endcomment %}
           <a class="btn Icona">
            <img class="DislikeIcon" data-pressed="{{post.postinfo_set.all|has_disliked:user}}" data-post-id="{{post.pk}}" src="{% static 'img/dislike.png' %}"/>
           </a>
           {% endif %}
          </div>
         </div>
        </div>
       </div>
       {% endif %}
      </div>
     </div>
    {% endfor %}
    
    {% comment %} <div class="row OnePostContent">
     <div class="col OnePostBack PostWithoutCheck PostChecked">
      <button class="ButtonSetting">
       <img class="SettingIcon" src="{% static 'img/Шестерёнка.png' %}"/>
      </button>
      <h2 class="PersonName">
       Имя пользователя
      </h2>
      <div class="row">
       <div class="col-3 MyCity">
        <p>
         Петропавловск-Камчатский
        </p>
       </div>
       <div class="col-3 rating">
        <p>
         Рейтинг
        </p>
       </div>
      </div>
      <p class="review">
       Сам отзыв
      </p>
      <div class="row LikesAndDislikes">
       <div class="col-6 Likes">
        <div class="row">
         <div class="col">
          <p class="LikesAmount p1 text-center">
           Лайков:
          </p>
          <p class="amountL p1 text-center">
           ...
          </p>
         </div>
         <div class="col ForIcona">
          <button class="Icona">
           <img class="LikeIcon" src="{% static 'img/Лайк.png' %}"/>
          </button>
         </div>
        </div>
       </div>
       <div class="col-6 Dislikes">
        <div class="row">
         <div class="col">
          <p class="DislikesAmount p1 text-center">
           Дизлайков
          </p>
          <p class="amountD p1 text-center">
           ...
          </p>
         </div>
         <div class="col ForIcona">
          <button class="Icona">
           <img class="DislikeIcon" src="{% static 'img/Дизлайк.png' %}"/>
          </button>
         </div>
        </div>
       </div>
      </div>
     </div>
    </div> {% endcomment %}
   </div>
  </div>
  <script>
    window.likeSprites = {
           normal: "{% static 'img/like.png' %}",
           pressed: "{% static 'img/like_pressed.png' %}",
       };
       window.dislikeSprites = {
           normal: "{% static 'img/dislike.png' %}",
           pressed: "{% static 'img/dislike_pressed.png' %}",
       };
   </script>
   <script src="{% static 'js/posts_myPosts.js' %}"></script>
 </body>
</html>

ChingChong/templates/posts/api_posts.html
{% load static %}
{% load custom_filters %}
{% for post in posts %}
<div class="row OnePostContent">
  <div class="col OnePostBack">
   {% if perms.posts.change_post %}
   <button class="ButtonSetting">
     <a href="{% url 'admin:posts_post_change' post.pk %}"><img class="SettingIcon" src="{% static 'img/Шестерёнка.png' %}"/></a>
   </button>
   {% endif %}
    <h2 class="PersonName">
    Пользователь: <a href={% url 'profile'%}{{post.sender.username}} style="text-decoration: none; color: black;">
      {{post.sender.username}}
    </a>
   </h2>
   <div class="row">
    <div class="col-3 MyCity">
     <p>
      Город: {{post.restaurant.adress|default:"--------"}}
     </p>
    </div>
    <div class="col-3 rating">
     <p>
      Рейтинг: {{post.get_rating_display}}
     </p>
    </div>
   </div>
   <p class="review">
    {{post.review}}
   </p>
   <div class="row LikesAndDislikes">
    <div class="col Likes">
     <div class="row">
      <div class="col-6 text-center">
       <p class="LikesAmount p1">
        Лайков:
       </p>
       <p class="amountL p1">
         {{post.postinfo_set.all|count_rating:1}}
       </p>
      </div>
      <div class="col-6 ForIcona">
       {% if user.is_authenticated %}
       <a class="btn Icona">
        <img class="LikeIcon" data-pressed="{{post.postinfo_set.all|has_liked:user}}" data-post-id="{{post.pk}}" src="{% static 'img/like.png' %}"/>
       </a>
       {% endif %}
      </div>
     </div>
    </div>
    <div class="col Dislikes">
     <div class="row">
      <div class="col-6 text-center">
       <p class="DislikesAmount p1">
        Дизлайков:
       </p>
       <p class="amountD p1">
         {{post.postinfo_set.all|count_rating:-1}}
       </p>
      </div>
      <!-- <div class="col ForIcona"><button class="Icona"><img class="DislikeIcon" src="img/Дизлайк.png"></button></div> -->
      <div class="col-6 ForIcona">
       {% if user.is_authenticated %}
       <a class="btn Icona">
        <img class="DislikeIcon" data-pressed="{{post.postinfo_set.all|has_disliked:user}}" data-post-id="{{post.pk}}" src="{% static 'img/dislike.png' %}"/>
       </a>
        {% endif %}
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
 </div>
  {% endfor %}

ChingChong/templates/posts/oldapi_posts.html
{% load static %}
{% load custom_filters %}
{% for post in posts %}
    <div class="row OnePostContent">
      <div class="col OnePostBack">
      {% if perms.posts.change_post %}
      <button class="ButtonSetting">
        <a href="{% url 'admin:posts_post_change' post.pk %}"><img class="SettingIcon" src="{% static 'img/Шестерёнка.png' %}"/></a>
      </button>
      {% endif %}
       <h2 class="PersonName">
        Пользователь: {{post.sender.username}}
       </h2>
       <div class="row">
        <div class="col-3 MyCity">
         <p>
          Город: {{post.restaurant.adress|default:"--------"}}
         </p>
        </div>
        <div class="col-3 rating">
         <p>
          Рейтинг: {{post.get_rating_display}}
         </p>
        </div>
       </div>
       <p class="review">
        {{post.review}}
       </p>
       <div class="row LikesAndDislikes">
        <div class="col-3 Likes">
         <div class="row">
          <div class="col-auto text-center">
           <p class="LikesAmount p1">
            Лайков:
           </p>
           <p class="amountL p1">
            {{post.postinfo_set.all|count_rating:1}}
           </p>
          </div>
          <div class="col-auto ForIcona">
            {% if user.is_authenticated %}
           {% comment %} <button class="Icona">
            <a href="{% url 'api_post_like' post.pk %}"><img class="LikeIcon" src="{% static 'img/Лайк.png' %}"/></a>
           </button> {% endcomment %}
           <a class="btn Icona">
            <img class="LikeIcon" data-pressed="{{post.postinfo_set.all|has_liked:user}}" data-post-id="{{post.pk}}" src="{% static 'img/like.png' %}"/>
           </a>
           {% endif %}
          </div>
         </div>
        </div>
        <div class="col-3 Dislikes">
         <div class="row">
          <div class="col-auto text-center">
           <p class="DislikesAmount p1">
            Дизлайков:
           </p>
           <p class="amountD p1">
            {{post.postinfo_set.all|count_rating:-1}}
           </p>
          </div>
          <div class="col-auto ForIcona">
            {% if user.is_authenticated %}
           {% comment %} <button class="Icona">
            <a href="{% url 'api_post_dislike' post.pk %}"><img class="DislikeIcon" src="{% static 'img/Дизлайк.png' %}"/></a>
           </button> {% endcomment %}
           <a class="btn Icona">
            <img class="DislikeIcon" data-pressed="{{post.postinfo_set.all|has_disliked:user}}" data-post-id="{{post.pk}}" src="{% static 'img/dislike.png' %}"/>
           </a>
           {% endif %}
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
    {% endfor %}